### ISSUE TITLE
Renommer le README en README.md

### ISSUE THREAD

**Issue by jpainam** [ndoubayo/webhtmCSS#1]
Peux tu renommer le fichier readme en `README.md`, ceci permet d'avoir un bon format.

**Comment by ndoubayo** [comment]
Bonjour Monsieur,
Je viens par la présente note vous faire part de la correction du fichier
Readme que vous m'avez suggérer .
Merci pour vos remarques. Je reste à l'écoute pour d'avantage conseils.
Recevez toutes mes salutations distinguées.

**Comment by jpainam** [comment]
D'accord, j'ai vérifié ,  c'est bon.
