### ISSUE TITLE
renommer le fichier du point d'entree du site 

### ISSUE THREAD

**Issue by jpainam** [ndoubayo/webhtmCSS#3]
Bonjour.
Le premier fichier a ouvrir pour accéder au site doit être nommer de preference `index.html` 
Je crois qu'il faut renommer `booki.html` en `index.html`.

Et si tu as beaucoup de fichier `.css` ou des fichiers de styles, met les tous dans le sous dossier `styles` et tu les importe depuis ce sous dossier.

**Comment by ndoubayo** [comment]
Bonjour Monsieur,
Je viens vous informer que j'ai déjà remedier à votre suggestion.
Merci.

**Comment by ndoubayo** [comment]
Bonjour Monsieur,
J'espère que vous allez bien.
Je viens par la presente note vous demander d'avantage de directives.
En effet j'ai une copie du travail que je fais en paralèlle de celui-ci.
Je vous voudrai savoir si ça ne pourrai pas poser de problème au cas où je compte changer tout le contenu du code.
En effet je comprend mieux le 2e travail que j'ai fais.

Merci pour la compréhension.

**Comment by jpainam** [comment]
Le deuxième travail porte toujours sur le même projet? Si c’est le cas. Tu n’a pas besoin de supprimer les fichiers actuels. 
tu px faire un push avc l’option - - force

si c’est carement un autre projet. C’est mieux de creer un autre dépôt (repositort)

**Comment by ndoubayo** [comment]
Salut Monsieur, 
Merci pour votre réponse.
Au fait c'est le même projet. Je ne veux rien supprimer je voudrai juste copier-coller les contenus dans les fichiers actuels.
Par contre je comprend pas encore bien l'option - -force.

Merci

**Comment by jpainam** [comment]
Ah d’accord. J vx juste dire q meme si tu creai un n’ouvre projet et tu réinitialise git dans l nouveau dossier. Tu px uploader ces fichiers ici.

**Comment by ndoubayo** [comment]
Bonjour Monsieur,
Je vous remercie pour votre aide et considération.

Je reste à votre écoute pour d'amples conseils concernant l'évolution de mon travail.
Merci.

**Comment by jpainam** [comment]
D’accord
